name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '*.rst'
      - 'LICENSE'
      - 'dev_requirements.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - '*.rst'
      - 'LICENSE'
      - 'dev_requirements.txt'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        include:
          - os: ubuntu-latest
            python-version: 3.4
          - os: ubuntu-latest
            python-version: pypy2
          - os: ubuntu-latest
            python-version: pypy3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python Env
        uses: actions/setup-python@v2.1.4 # FIXME: Use "v2" tag once https://github.com/actions/setup-python/issues/171 is resolved.
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          make init
          pip install coveralls
      - name: Run Tests
        run: |
          make test
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          coveralls
